### ISSUE TITLE
How to handle cmake presets with older versions of cmake-gui

### ISSUE THREAD

**Issue by Deakon997** [RA-Consulting-GmbH/openscenario.api.test#102]
**Describe the bug:**
The documentation misses information how to use older versions of cmake-gui without preset selection capabilities.

**Expected behavior:**
The documentation should have a section how presets are selected with older versions of cmake-gui.

**Comment by arauschert** [comment]
Presets are available starting from cmake version 3.19. The latest Ubuntu 20.04.2 LTS provides cmake v3.16.3-1ubuntu1 (see https://packages.ubuntu.com/focal/devel/ ). So I assume it makes sense to provide support for cmake version without presets for some more time.

**Comment by Deakon997** [comment]
Yes, that's right. The documentation has then two sections for describing the build process for cmake prior to version 3.19 and a section for cmake version >= 3.19.
Also I have already resurrected the generateLinux.sh script taking care of automatic building and compiling OpenSCENARIO for older cmake versions and for newer cmake versions.
An update for Linux will be available today for both the documentation and the build script.

**Comment by Deakon997** [comment]
Solved and merged in the current dev branch
