### ISSUE TITLE
IsSet...() methods return false, if parameters or expressions are used as value

### ISSUE THREAD

**Issue by arauschert** [RA-Consulting-GmbH/openscenario.api.test#137]
**Describe the bug**
When using the new IsSet...() functions, they return false although the attribute is set in the scenario. This only happens, if the value is not hardcoded, but a referenced parameter or an expression.

**To Reproduce**
1. Parse example scenario: https://github.com/asam-oss/OSC-ALKS-scenarios/blob/master/Scenarios/ALKS_Scenario_4.4_1_CutInNoCollision_TEMPLATE.xosc
2. Execute IsSetDs() for the element RelativeLanePosition in line 113

**Expected behavior**
IsSetDs() returns true.

**SW-version**
OSC API 1.2.1

**Comment by muzair-RAC** [comment]
Bug fixed in branch issue-137-isset-methods. The branch will be merged with master

**Comment by muzair-RAC** [comment]
This bug fix relates to issue #138. the previous separate fix in branch issue-137-isset-methods is reflected in branch 138-schema-validation. Branch  issue-137-isset-methods was removed
