### ISSUE TITLE
Validation of unsignedInt insufficent (Example: ManeuverGroup::maximumExecutionCount)

### ISSUE THREAD

**Issue by reneparis** [RA-Consulting-GmbH/openscenario.api.test#198]
**Describe the bug**

The attribute `maximumExecutionCount` of the element `ManeuverGroup` (https://www.asam.net/static_downloads/ASAM_OpenSCENARIO_V1.1.1_Model_Documentation/modelDocumentation/content/ManeuverGroup.html) is an `unsignedInt` with range `[1...inf[`. 

There is no possibility to specifiy infinite at all. "INF" or "inf" or "-1" always leads to a validation error. I understand that this is a restriction of the datatype itself. So our users started to use "other ways" to make it clear, that we wanna have infinite execution.

Unfortunately, even if the user typed some unparseable strings starting with an alphanumeric character, parsing silently continued and used the wrong numbers.

**To Reproduce**

Try to validate a scenario file with the following configuration:
- `<ManeuverGroup maximumExecutionCount="1E6">` leads to `GetMaximumExecutionCount() == 1`
- `<ManeuverGroup maximumExecutionCount="100.000.000">` leads to `GetMaximumExecutionCount() == 100`
- `<ManeuverGroup maximumExecutionCount="100,000,000">` leads to `GetMaximumExecutionCount() == 100`
- `<ManeuverGroup maximumExecutionCount="1OoO1">` leads to `GetMaximumExecutionCount() == 1`

**Expected behavior**

- In all aforementioned examples, the validation should FAIL
- In the ideal case "INF" or "inf" is mapped to a `IsMaximumExecutionCountInf()` method and maximumExecutionCount is set to `uint32::max` internally.

**Desktop (please complete the following information):**

 - OS: Debian 11

**Comment by ahege** [comment]
Thank you for your ticket. We will investigate the bug as soon as we can. We are planning a bugfix release for October.

**Comment by kmfrank** [comment]
fixed

**Comment by arauschert** [comment]
Validation now fails for the examples.
"INF" and "inf" can not be parsed and result in an error as well.
