### ISSUE TITLE
OpenScenarioXMLExporter does not add xml declaration

### ISSUE THREAD

**Issue by shankarpatali-stla** [RA-Consulting-GmbH/openscenario.api.test#201]
**Describe the bug**
OpenScenarioXmlExporter::CreateXmlDocument does not add XML declaration. XML declaration is typically the first line in the file. For example, `<?xml version="1.0" encoding="utf-8"?>`.

**To Reproduce**
1. Create pointer to a valid scenario object of type `std::shared_ptr<IOpenScenarioWriter>`
2. Call OpenScenarioXmlExporter::CreateXmlDocument. Pass the pointer created in step 1 as input parameter.
3. Store the return value in std::shared_ptr<tinyxml2::XMLDocument>
4. Print the xml document.

Sample code:
```
// Get valid scenario
std::shared_ptr<IOpenScenarioWriter> scenario_ptr = GetValidScenario();
// Create xml document
OpenScenarioXmlExporter scenario_xml_exporter;
std::shared_ptr<tinyxml2::XMLDocument> xml_document = scenario_xml_exporter.CreateXmlDocument(scenario_ptr);
// Print xml document
tinyxml2::XMLPrinter printer;
xml_document->RootElement()->Accept(&printer);
std::cout << printer.CStr() << std::endl;
```

**Expected behavior**
XML Declaration is present the XML document returned by CreateXmlDocument function.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by NoahSchickIntech** [comment]
I wouldn't classify this as a bug. Yes, "[XML documents SHOULD begin with a declaration](https://www.w3.org/TR/xml/#sec-prolog-dtd:~:text=XML%20documents%20should%20begin%20with%20an%20XML%20declaration)" but only "[XML 1.1 documents MUST begin with a declaration](https://www.w3.org/TR/xml11/#dt-valid:~:text=XML%201.1%20documents%20must%20begin%20with%20an%20XML%20declaration)"

**Comment by ahege** [comment]
OK, I think we should fiy this. Start an export with xml declaration.
