### ISSUE TITLE
XML export wrong for CustomCommandAction element

### ISSUE THREAD

**Issue by shankarpatali-stla** [RA-Consulting-GmbH/openscenario.api.test#204]
**Describe the bug**
When exporting a scenario to XML with the OpenScenarioXmlExporterV1_2, then the elements for Storyboard/Story/Act/ManeuverGroup/Maneuver/Event/Action/UserDefinedAction/CustomCommandAction are wrong. The content text is added as an attribute. Instead it must be added just as text under CustomCommandAction element.

Refer: https://www.asam.net/static_downloads/ASAM_OpenSCENARIO_V1.2.0_Model_Documentation/modelDocumentation/content/CustomCommandAction.html

**To Reproduce**
1. Parse xosc scenario with CustomCommandAction element
2. Write xosc scenario with OpenScenarioXmlExporterV1_2
3. investigate tiny xml output

**Expected behavior**
The content text is added just as text under CustomCommandAction
![image](https://github.com/RA-Consulting-GmbH/openscenario.api.test/assets/140606521/a91eb2e8-be44-4512-bc9a-43060124d97b)

**Screenshots**
![image](https://github.com/RA-Consulting-GmbH/openscenario.api.test/assets/140606521/ad8f40bf-7a8c-4abb-b636-88fdbf9cf59f)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kmfrank** [comment]
fixed

**Comment by arauschert** [comment]
The fix works, just the formatting gets lost while writing.
This is the original scenario:
```xml
                <UserDefinedAction>
                  <CustomCommandAction type="Test">
                    This is copied correctly!  <![CDATA[Inhalt]]>
                  </CustomCommandAction>
                </UserDefinedAction>
```

After parsing and writing the formatting looks like this:
```xml
                                <UserDefinedAction>
                                    <CustomCommandAction type="Test">
                    This is copied correctly!  Inhalt</CustomCommandAction>
                                </UserDefinedAction>
```
