### ISSUE TITLE
GetSeconds is not exported

### ISSUE THREAD

**Issue by arauschert** [RA-Consulting-GmbH/openscenario.api.test#208]
**Describe the bug**
There is a method to get the seconds from the DateTime struct called "GetSeconds":
https://github.com/RA-Consulting-GmbH/openscenario.api.test/blob/6c6d6c43764029033b35987d1b8d69cea3a873f0/cpp/openScenarioLib/src/common/DateTime.h#L41

It cannot be used from outside the library because it's not prefixed with the OPENSCENARIOLIB_EXP macro/define.

**To Reproduce**
Write a small program that includes the osc api and wants to use the GetSeconds(). It won't compile/link.

**Expected behavior**
GetSeconds() can be used from outside the library.

**Additional context**
Used in this MR: https://gitlab.eclipse.org/eclipse/openpass/openscenario1_engine/-/merge_requests/190

**Comment by kmfrank** [comment]
fixed and tested
