### ISSUE TITLE
Add Getting Started for C++

### ISSUE THREAD

**Issue by ahege** [RA-Consulting-GmbH/openscenario.api.test#35]
I think it is transparent what to do when you read the Java "Getting Started".
Though we should add the exact same examples with C++ code.

**Comment by Deakon997** [comment]
@ahege: if the current "Getting Started" for C++ is ok for you, then I will close the ticket.

**Comment by reneparis** [comment]
As its part of the C++ Guide and the issue is still open: There is a (minor) typo in the guide:  `generateLinux.sh`  -> `generate_Linux.sh`
