### ISSUE TITLE
Provide constants for C++ types

### ISSUE THREAD

**Issue by ahege** [RA-Consulting-GmbH/openscenario.api.test#39]
As we cannot use reflection in C++ like in java (`this.getClass().getName()`) I suggest a general concept for runtime types. This is usual in many c++ frameworks

The typenames are then used in runtime (e.g. in `GetAdapter` for parameter `classifier`)

```cpp
virtual std::shared_ptr<void> GetAdapter(const std::string classifier)
```

(Suggestion follows)

**Comment by ahege** [comment]
In every generated and  manual written class (and interface), add a constant with the runtime name.
Important: Add namespace in value to be able to distinguish between versions.

E.g. 

In generated IAbsoluteSpeed: 

const std::string RT_TYPE__I_ABSOLUTE_SPEED = "NET_ASAM_OPENSCENARIO::V_1_0::IAbsoluteSpeed";

In IOpenScenarioModelElement

const std::string RT_TYPE__I_ABSOLUTE_SPEED = "NET_ASAM_OPENSCENARIO::IOpenScenarioModelElement";


We than can use in GetAdapter:

```cpp
virtual std::shared_ptr<void> GetAdapter(const std::string classifier) {
                
				...
				if (classifier == NET_ASAM_OPENSCENARIO::V_1_0::RT_TYPE__I_ABSOLUTE_SPEED)
				{
					return shared_from_this();
				}
};
```

We can try to generalize this with MACROS like described [here](https://gist.github.com/patrickBerry/8cf7799066aaf01d1b8fdab1622c1186) but I do not think it is necessary at this point in time.

**Comment by ahege** [comment]
@muzair-RAC: What do you thin?

**Comment by ahege** [comment]
@muzair-RAC: I have just studied your code and learned that you are already using something like this:
E.g. in RangeCheckerRule

typeid(ILocator).name() for the  `classifier` attribute in `getAdapter`. So I think the constants are not needed. Is this right? This would be great as this redundant information sucks a little bit.

On the other hand, we need the namespace included in the identifier, so let's check out what have to be done. Probably we have to work with the `std::type_info` typed value in the `GetAdpater`, which is ok:

```cpp
virtual std::shared_ptr<void> GetAdapter(const std::type_info classifier) {
                
				...
				if (classifier == typeid(ILocator))
				{
					return shared_from_this();
				}
};
```

**Comment by muzair-RAC** [comment]
@ahege: The code right now uses typeid includes the namespace including the version dependent part of namespace.
typeid().name() returns a string describing the class.

example 
typeid(ILocator).name() => "class NET_ASAM_OPENSCENARIO::ILocator"
typeid(IScenarioChecker).name() => "class NET_ASAM_OPENSCENARIO::V_1_0::IScenarioChecker"

I think this is all that you wanted to implement. Or am I missing something?

**Comment by ahege** [comment]
Very good, I looked into [this ](https://en.cppreference.com/w/cpp/language/typeid) example and my impression was that name() returns just the name without namespace like "IAction". But if you tested the function and it returns a unique id in terms of namespace and class name, this is exactly what we need.

So, when shared_from_this works, I would give it a shot.
