### ISSUE TITLE
Add system exit codes for standalone checker

### ISSUE THREAD

**Issue by ahege** [RA-Consulting-GmbH/openscenario.api.test#48]
**Is your feature request related to a problem? Please describe.**
Standalone checker: CI project requires system exits (0 for success, 1 for error, see below). Implement it in C++ and Java

**Describe the solution you'd like**
0 for success.
1 when -v (version) option with the command line
2 when the command line is empty (show "Usage..."
3 for any error (program error or when one or more files cannot be validated (files have errors).

**Additional context**
@ahege will make a branch with the java solution, @uzair18 may follow later with C++.

**Comment by ahege** [comment]
Now we have implemented exit codes (differ from the original definition above)

0 for success.
1 for any error (program error or when one or more files cannot be validated (files have errors).
2 when the command line is empty (show "Usage..."
3 when -v (version) option with the command line

**Comment by ahege** [comment]
@muzair-RAC, can you check the [Getting started article](https://github.com/RA-Consulting-GmbH/openscenario.api.test/wiki/Getting-started-cpp) for the new command line output?
(-d option)

**Comment by muzair-RAC** [comment]
@ahege, Its updated now to reflect the new output and parameters
