### ISSUE TITLE
Being tolerant in parameter types

### ISSUE THREAD

**Issue by ahege** [RA-Consulting-GmbH/openscenario.api.test#53]
**Is your feature request related to a problem? Please describe.**
When a $-notated parameter value does not match the type of the defined parameter, at the moment a error is issued.

Being more tolerant here might help.

Example (not tolerant)
```xml
    <ParameterDeclaration name="laneId" parameterType="integer" value="-4" />
```
where type string is expected:

```xml
<LanePosition roadId="0" laneId="$laneId" offset="0.0" s="0.0"></LanePosition>
```
This issues an error. In LanePosition laneId is expected to be a string.
 
**Describe the solution you'd like**
Make datatypes comaptible.

This is the proposal:
Every datatype should be compatible to String:
Further:
unsignedInt is compatible (convertable) to: double, unsignedShort (when target range fits), int (when target range fits)
unsignedShort is compatible to: double, int, unsignedInt (when target range fits)
int is compatible to: double, unsignedShort (when target range fits), unsignedInt (when target range fits)
double is compatible to: unsignedShort (when integer value and target range fits), unsignedInt (when integer value and target range fits ) int ( when integer value and target range fits ) 

All other datatypes are only compatible to String.

This code has to be adopted (ParameterResolver)

```java
public String findValue(Class<?> expectedParameterType, String parameterName) {
    // Search from the top of the stack (which is the end of the underlying
    // list)
    for (int i = this.parameterValueSets.size() - 1; i >= 0; i--) {
      Hashtable<String, ParameterValue> parameterNameToParameterValue =
          this.parameterValueSets.get(i);
      ParameterValue paramValue = parameterNameToParameterValue.get(parameterName);
      if (paramValue != null && paramValue.getType().equals(expectedParameterType)) {
        return paramValue.getValue();
      }
    }
    return null;
  }
```

**Comment by ahege** [comment]
@muzair-RAC: I try to make the changes step by step on the beeing_tolerant_on_paramters branch and with every commit I will document the changes.

1. Step.
Making the propertyToType map in the xImpl (ConditionImpl) more specific by using the concrete primitive type (e.g. integer) instead of the java class. Reason the class is umbiguous, unsigendShort and integer are represented by the same class (Integer) in java.

Before (e.g ConditionImpl): 
static {
    propertyToType.put(OscConstants.ATTRIBUTE__NAME, String.class);
    propertyToType.put(OscConstants.ATTRIBUTE__DELAY, Double.class);
    propertyToType.put(OscConstants.ATTRIBUTE__CONDITION_EDGE, String.class);
  }
After:

static {
    propertyToType.put(OscConstants.ATTRIBUTE__NAME, ParameterType.STRING);
    propertyToType.put(OscConstants.ATTRIBUTE__DELAY, ParameterType.DOUBLE);
    propertyToType.put(OscConstants.ATTRIBUTE__CONDITION_EDGE, ParameterType.STRING);
}

**Comment by ahege** [comment]
See last commit for first step.
Now second step: Issue a warning when parameter definition datatype cannot be converted in the target datatype.

**Comment by ahege** [comment]
See commit. Added also a ParameterDeclarationChecker in the XMLScenarioLoader.

**Comment by muzair-RAC** [comment]
@ahege The c++ implementation for this feature is complete.
