### ISSUE TITLE
File BOM Issue

### ISSUE THREAD

**Issue by ahege** [RA-Consulting-GmbH/openscenario.api.test#55]
**Describe the bug**
For antlr parsing when using utf-8, no BOM is assumed at the beginning of the file. If a BOM occurs, the parser issues an error

```
Checking 'D:\OSC-ALKS\OSC-ALKS-scenarios\Scenarios\ALKS_Scenario_4.3_1_FollowLeadVehicleComfortable_TEMPLATE.xosc'
line 1:0 extraneous input '?' expecting XMLDeclOpen
ERROR: Cannot resolve parameter 'Ego_InitPosition_LaneId' (50,41)
ERROR: Cannot resolve parameter 'Ego_InitPosition_LaneId' (69,41)
Validation failed with 2 errors and 0 warnings.
```

**To Reproduce**
1. Take a file with a BOM
2. Try to check it

**Expected behavior**
The BOM should be ignored  (or later taken to identify the encoding)

**Suggested Fix**
For now, ignore if there is a utf-8 BOM: 
utf-8 bom is a specific code at the beginning of the file:
EFBBBF stands for utf-8
(From net.asam.openscenario.v1_0.loader.XmlSceanrioLoader->load())

```java
BufferedInputStream bufferedInputStream = new BufferedInputStream(inputStream);
// Check BOM and skip utf 8 bom
byte[] buffer = new byte[3];
bufferedInputStream.mark(4);
int read = bufferedInputStream.read(buffer);
if (read <3)
{
 bufferedInputStream.reset();
}else if (buffer[0] != -17 || buffer[1] != -69 || buffer[2] != -65)
{
   // EF(-17) BB (-69) BF (-65)
   bufferedInputStream.reset();
}
      
stream = CharStreams.fromStream(bufferedInputStream);
XMLLexer lexer = new XMLLexer(stream);
CommonTokenStream tokens = new CommonTokenStream(lexer);
```

**Comment by ahege** [comment]
Fix also needed for C++. Add tests first. Then with failing tests, try to solve it.

**Comment by ahege** [comment]
@muzair-RAC I think fix it fist in the utf8-bom-issue branch

**Comment by muzair-RAC** [comment]
@ahege I merged my changes in this branch to the branch for issue #53
