### ISSUE TITLE
NameReferenceProxy SetTargetObject Compiler error

### ISSUE THREAD

**Issue by fjanssenluxoft** [RA-Consulting-GmbH/openscenario.api.test#63]
**Describe the bug**
If setting the target object inside a NamedReferenceProxy, gves an error regarding pointer usage:
> C:\work\openscenario.api.test\cpp\openScenarioLib\common\impl\NamedReferenceProxy.h(70,1): error C2228: left of '._targetObject' must have class/struct/union (compiling source file C:\work\osce\src\osci_core\src\NamedEntityReference.cpp)
> C:\work\openscenario.api.test\cpp\openScenarioLib\common\impl\NamedReferenceProxy.h(70,1): message : type is 'NET_ASAM_OPENSCENARIO::NamedReferenceProxy<NET_ASAM_OPENSCENARIO::V_1_0::IEntity> *' (compiling source file C:\work\osce\src\osci_core\src\NamedEntityReference.cpp)
> C:\work\openscenario.api.test\cpp\openScenarioLib\common\impl\NamedReferenceProxy.h(70,1): message : did you intend to use '->' instead? (compiling source file C:\work\osce\src\osci_core\src\NamedEntityReference.cpp)
> C:\work\openscenario.api.test\cpp\openScenarioLib\common\impl\NamedReferenceProxy.h(69): message : while compiling class template member function 'void NET_ASAM_OPENSCENARIO::NamedReferenceProxy<NET_ASAM_OPENSCENARIO::V_1_0::IEntity>::SetTargetObject(std::shared_ptr<T> &)'
>         with
>         [
>             T=NET_ASAM_OPENSCENARIO::V_1_0::IEntity
>         ] (compiling source file C:\work\osce\src\osci_core\src\NamedEntityReference.cpp)
> C:\work\osce\src\osci_core\src\NamedEntityReference.cpp(41): message : see reference to function template instantiation 'void NET_ASAM_OPENSCENARIO::NamedReferenceProxy<NET_ASAM_OPENSCENARIO::V_1_0::IEntity>::SetTargetObject(std::shared_ptr<T> &)' being compiled
>         with
>         [
>             T=NET_ASAM_OPENSCENARIO::V_1_0::IEntity
>         ]
> C:\work\openscenario.api.test\cpp\openScenarioLib\v_1_0\generated\impl\ApiClassImpl.h(3754): message : see reference to class template instantiation 'NET_ASAM_OPENSCENARIO::NamedReferenceProxy<NET_ASAM_OPENSCENARIO::V_1_0::IEntity>' being compiled (compiling source file C:\work\osce\src\osci_core\src\NamedEntityReference.cpp)

**To Reproduce**
1. Create application to load open scenario file with entity references
2. Call SetTargetObject of any of the entity references
3. Try to compile

**Expected behavior**
openscenario.api.test\cpp\openScenarioLib\common\impl\NamedReferenceProxy.h: 70 should be changed to `_targetObject = targetObject;` or similar

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Win10
 - Compiler: MSVC 19.27.29112.0

**Additional context**
n/a

**Comment by ahege** [comment]
@muzair-RAC, can you look at this reported bug?

**Comment by muzair-RAC** [comment]
@ahege I have pushed a fix for this bug on the master branch
