### ISSUE TITLE
C++ Parser error on resolving parameters when resolving parameter used in storyboard stop trigger

### ISSUE THREAD

**Issue by arauschert** [RA-Consulting-GmbH/openscenario.api.test#66]
**Describe the bug**
When using the C++ parser lib and parsing the scenario ALKS_Scenario_4.1_1_FreeDriving_TEMPLATE.xosc from the OSC-ALKS-scenarios repository, the parser gives an error:
Parse Cannot resolve parameter 'Duration' at line 98

Since the same scenario has already been parsed successfully with the Java version of the parser, we assume it´s a bug in the C++ version.

**Expected behavior**
No parser error.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Additional context**
[Link to scenario](https://github.com/arauschert/OSC-ALKS-scenarios/blob/master/Scenarios/ALKS_Scenario_4.1_1_FreeDriving_TEMPLATE.xosc)

**Comment by ahege** [comment]
Uzair, could you have a look at it?
