### ISSUE TITLE
Add Releases for referencing

### ISSUE THREAD

**Issue by arauschert** [RA-Consulting-GmbH/openscenario.api.test#68]
It would be great if the API also has release versions for referencing from other projects!

**Comment by ahege** [comment]
I am about consolidating the versions and tagging:

0.9.0 is the current version that BMW is using (from my knowledge). It is tagged and released
1.0.0 includes the writer-api. Also the gernerator is included.

THESE VERSIONS CAN BE FORKED FOR BUGFIXING AT ANY TIME.

Next Release 1.0.1 won't include code changes. We are heading for desupporting the java part of the API and might include some additional convenience for C++ cross compiling  with Cmake.
