### ISSUE TITLE
Constructor for enum types changes enum value

### ISSUE THREAD

**Issue by arauschert** [RA-Consulting-GmbH/openscenario.api.test#69]
**Describe the bug**
When constructing enum types like DynamicsShape, the constructor which takes the enum parameter changes the enum value.
The enum starts at -1 and the enum string vector indices at 0. I assume this must be fixed for all enum types, so it needs to be fixed in the code generator.

enum DynamicsShapeEnum
{
    UNKNOWN = -1,
    LINEAR,
    CUBIC,
    SINUSOIDAL,
    STEP,
};

private:
    std::string _literal;
    DynamicsShapeEnum _dynamicsShapeEnum;
    static std::map<std::string, DynamicsShapeEnum> _stringToEnum;

public:
const std::vector<std::string> kDynamicsShapeEnumString 
{
    "UNKNOWN",
    "linear",
    "cubic",
    "sinusoidal",
    "step",
};

DynamicsShape(DynamicsShapeEnum& dynamicsShape)
{
    _literal = kDynamicsShapeEnumString[dynamicsShape]; **<== must be dynamicsShape+1**
    _dynamicsShapeEnum = GetFromLiteral(_literal);
}

**Comment by ahege** [comment]
@muzair-RAC. Can you fix that? It should not be too much work. You have to use the geerator that is still available in th RAC's repository.

**Comment by muzair-RAC** [comment]
@ahege Sorry I just saw this today. This is already fixed in the writer-api branch but I will copy these changes in the master branch as well tomorrow.

**Comment by arauschert** [comment]
Sorry to reopen, but the fix made some part of the code in the assignment operator obsolete, which could be removed now. Please see my comment here:
https://github.com/RA-Consulting-GmbH/openscenario.api.test/commit/6fa20f311a7964d7286e1138b59b9fa03aad8196

**Comment by muzair-RAC** [comment]
@arauschert  thanks for pointing it out.
