### ISSUE TITLE
const correctness for Getters of c++ ApiClassInterfaces.h

### ISSUE THREAD

**Issue by reneparis** [RA-Consulting-GmbH/openscenario.api.test#70]
I'm used to use `const` as much as possible to make my intentions in code pretty clear.
When i tried to compile against the API and realized, that none of the methods provided are `const`.

I don't see a reason not to do so, so I ask you, if you see anything speaking against it.
BTW: Can you point me to the places, where the changes needs to be done (e.g. for a pull-request)?

Thanks

**Comment by muzair-RAC** [comment]
Hi 

I have made the change in writer-api branch which will be merged with master soon.  I don't understand which changes are you talking about for pull-request. [Here ](https://github.com/RA-Consulting-GmbH/openscenario.api.test/wiki/General-Architectural-Aspects)is a link to general guidelines.
Thanks

**Comment by ahege** [comment]
For the common understanding. These chages took effect in the 0.9.0 release.

The library v1.0.0 must be equipped with these changes in the next release.
