### ISSUE TITLE
Dark Mode Theme Support for TemplateEditor (de.rac.groovy.extension.feature.zip)

### ISSUE THREAD

**Issue by reneparis** [RA-Consulting-GmbH/openscenario.api.test#74]
The provided template editor (see feature-branch writer-api) does not respect the OS theme settings, which makes it impossible to use with eclipse in dark mode:

![image](https://user-images.githubusercontent.com/11086497/116511240-7089c480-a8c6-11eb-9125-7d10cfcf2509.png)

- OS: Debian Bullseye 
- Desktop: KDE Plasma 5.20.5
- Theme: Breeze Dark
- Eclipse: 4.19.0

**Comment by ahege** [comment]
Added new template plugin. Please see the release notes and the updated documentation for the generator.
I am closing this issue. Please re-open it or contritbute another issue for bugs.
