### ISSUE TITLE
JRE version requirement missing (de.rac.openscenario.generator)

### ISSUE THREAD

**Issue by reneparis** [RA-Consulting-GmbH/openscenario.api.test#75]
Code generation fails, when the JDK version is too new.

- It works with openJRE 11.0.11
- But fails with 17 and presumably 15 too.

Feature-branch: writer-api (d75c55f)
OS: Debian Bullseye
IDE: Eclipse 4.19.0

**Comment by ahege** [comment]
@reneparis, Please check the generator. I've added the java version.
